# Generated by Django 5.1 on 2024-09-08 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[a-zA-Z])(?=.*[\\W\\d\\s:])([^\\s]){8,16}$', ['password must contain 1 number (0 - 9)', 'password must contain 1 uppercase letters', 'password must contain 1 lowercase letters', 'password must contain 1 non-alpha numeric character', 'password must be 8-16 characters with no space'])]),
        ),
        migrations.AlterModelTable(
            name='blacklistmodel',
            table='blacklist',
        ),
    ]
