# Generated by Django 5.1 on 2024-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'currency',
                'unique_together': {('currency_code', 'updated_at')},
            },
        ),
    ]
