# Generated by Django 5.1 on 2024-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listingmodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='region',
            field=models.CharField(choices=[(1, 'VINNYTSIA'), (2, 'VOLYN'), (3, 'DNIPRO'), (4, 'DONETSK'), (5, 'IVANO-FRANKIVSK'), (6, 'KHERSON'), (7, 'KHMELNYTSKYI'), (8, 'KYIV'), (9, 'KYIV OBLAST'), (10, 'KIROVOHRAD'), (11, 'LUHANSK'), (12, 'LVIV'), (13, 'MYKOLAIV'), (14, 'ODESA'), (15, 'POLTAVA'), (16, 'RIVNE'), (17, 'SUMY'), (18, 'TERNOPIL'), (19, 'KHARKIV'), (20, 'ZAPORIZHZHIA'), (21, 'ZHYTOMYR'), (22, 'CHERKASY'), (23, 'CHERNIVTSI'), (24, 'CHERNIHIV'), (25, 'CRIMEA')], default='KYIV', max_length=50),
        ),
    ]
