# Generated by Django 5.1 on 2024-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingmodel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='initial_currency_rate',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=10, null=True),
        ),
    ]
