# Generated by Django 5.1 on 2024-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingmodel_initial_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='profanity_checked',
            field=models.BooleanField(default=False),
        ),
    ]
