# Generated by Django 5.1 on 2024-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingmodel_profanity_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='profanity_checked',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Moderation'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=10),
        ),
    ]
