# Generated by Django 5.1 on 2024-09-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listingmodel_profanity_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='status',
        ),
    ]
