# Generated by Django 5.1 on 2024-09-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listingmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='region',
            field=models.CharField(choices=[(1, 'CRIMEA'), (2, 'VINNYTSIA'), (3, 'VOLYN'), (4, 'DNIPRO'), (5, 'DONETSK'), (6, 'IVANO-FRANKIVSK'), (7, 'KHERSON'), (8, 'KHMELNYTSKYI'), (9, 'KYIV'), (10, 'KIROVOHRAD'), (11, 'LUHANSK'), (12, 'LVIV'), (13, 'MYKOLAIV'), (14, 'ODESA'), (15, 'POLTAVA'), (16, 'RIVNE'), (17, 'SUMY'), (18, 'TERNOPIL'), (19, 'KHARKIV'), (20, 'ZAPORIZHZHIA'), (21, 'ZHYTOMYR'), (22, 'CHERKASY'), (23, 'CHERNIVTSI'), (24, 'CHERNIHIV')], default='KYIV', max_length=50),
        ),
    ]
